import {
  w1,
  w2,
  w3,
  w4,
  epa1,
  epa2,
  epa3,
  epa4,
  epb1,
  epb2,
  epb3,
  epb4,
  epc1,
  epc2,
  epc3,
  epc4,
  hpa1,
  hpa2,
  hpa3,
  hpa4,
  hpb1,
  hpb2,
  hpb3,
  hpb4,
  hpc1,
  hpc2,
  hpc3,
  hpc4,
  sp1,
  sp2,
  sp3,
  sp4,
} from './assets'
export const Products = [
  {
    img1:  sp1 ,
    img2:  sp2 ,
    img3:  sp3 ,
    img4:  sp4 ,
    name: 'boAt Party Pal 50',
    rate: 4,
    rates: 20,
    details:
      'Immerse in the 20W RMS Stereo Sound with the powerful Party Pal 50 bluetooth speaker. Set the vibes of the party just right with the RGB LEDs. Keep worries at bay and party poolside with IPX5 splash resistant! Get, set, grooving as Party Pal 50 comes with a powerful playback of 4.5 Hrs. Access Instant Voice Assistant and enjoy the multiple connectivity modes- USB, AUX, Bluetooth v5.1, and FM. Coming with Type-C interface, Party Pal 50 is all you need to set the mood just about right. So, where y’all partying at?',
    price: 56,
  },
  {
    img1:  hpa1 ,
    img2:  hpa2 ,
    img3:  hpa3 ,
    img4:  hpa4 ,
    name: 'boAt Rockerz 451',
    rate: 4,
    rates: 20,
    details:
      'Set your mind ablaze with boAt Rockerz 450 — our slick headphones that offer immersive sound quality and add luxury to your sound. Propelled by crystal clear 40mm dynamic drivers, slip into an alternate HD immersive audio reality. The soft cornered matte black finish allows for a comfortable fit, propagated by plush foam in adaptive and adjustable design. Choose your mode, go wireless with Bluetooth V4.2 or connect an aux wire that doesn’t cause any drain on the 300mAh rechargeable lithium battery.',
    price: 49,
  },
  {
    img1:  hpb1 ,
    img2:  hpb2 ,
    img3:  hpb3 ,
    img4:  hpb4 ,
    name: 'boAt Immortal 1000D',
    rate: 4,
    rates: 20,
    details:
      'The game begins here. With Immortal 1000D gaming headphones, don’t just play the game - feel it, live it, and own it. Level up your audio game with 7.1 Channel Surround Sound and Dolby Atmos that unleashes the winning beast inside you. Equipped with 50mm drivers, get a powerful 360° gaming experience like no other. Now, you can conquer every game with a sound that provides position accuracy and abstracts. Your everyday gaming is now double the fun with its RGB LED lights. Its lightweight and ergonomic build ensure you have a comfortable bender with your friends. Don’t look further, level up with Immortal 1000D headphones.',
    price: 50,
  },
  {
    img1:  hpc1 ,
    img2:  hpc2 ,
    img3:  hpc3 ,
    img4:  hpc4 ,
    name: 'BOAT BassHeads 900',
    rate: 4,
    rates: 20,
    details:
      'The boAt BassHeads 900 wired headphones come with an amalgamation of style with performance. Now get ready to enjoy your favourite tunes with Super Extra Bass and crystal-clear sound performance with Bass Heads 900 wired headphones. Experience powerful, dynamic sound with punchy bass and clear, natural vocals with the responsive 40mm Neodymium drivers, the drivers effectively reproduce sound equally across the whole audio band. The ergonomic design creates passive attenuation of ambient noise while providing maximum comfort for hours of listening pleasure in a snuggly fit without fatigue. The sleek, lightweight, and compact design makes portability extremely convenient. The foldable and compact Feather Light Headphone weighs even less than 150 g, moreover, the ear cups can be folded for easy, convenient storage.',
    price: 49,
  },
  {
    img1:  epa1 ,
    img2:  epa2 ,
    img3:  epa3 ,
    img4:  epa4 ,
    name: 'boAt BassHeads 242',
    rate: 4,
    rates: 20,
    details:
      'Get ready to redefine fitness fashion and utility with the wired headphone boAt Bassheads 242, it’s time to get your sport on. It carries ear hooks that are crafted from silicon to maximize comfort and a secure fit that allows you to maximize your workouts. Coated with IPX 4 sweat and water protection, the Bassheads 242 emphasizes on all-around ability with 10mm drivers that reproduce a quality sound. Move around freely with the superior coated cable that reaches comfortably from your pocket till your ears. Connect to a number of devices with ease using the 3.5mm straight jack, because there’s no stress, only sweetness when you’re riding the waves on this boAt. You can tune in and out with the pause/play button that can also take calls (With In-line Mic.) and control volume in-between exercise reputations.',
    price: 34,
  },
  {
    img1:  epb1 ,
    img2:  epb2 ,
    img3:  epb3 ,
    img4:  epb4 ,
    name: 'BOAT Airdopes 281 Pro',
    rate: 4,
    rates: 20,
    details:
      'Life seems better if the right music is heard the right way. Plug into a blissful listening experience with boAt Airdopes 281 Pro - a truly wireless earbuds powered by boAt Signature Sound. Equipped with ENx™ Technology and four mics, it makes your everyday calling experience hit the roof. Win matches while playing multiplayer games with your friends through its optimum noise cancellation and crystal-clear audio input. So, where are you? Because your perfect audio match is right here - boAt Airdopes 281.',
    price: 69,
  },
  {
    img1:  epc1 ,
    img2:  epc2 ,
    img3:  epc3 ,
    img4:  epc4 ,
    name: 'boAt Rockerz 333',
    rate: 4,
    rates: 20,
    details:
      'When your taste in music is so unique, why should your audio wear be any different? Speak your unique style with Rockerz 333 - a bold and powerful wireless earphones for the part of you that wants more. More of sound, more of style, and more of power. Immerse into your jam with boAt Signature Sound and 30 HRS of non stop playback. Let nothing limit your hustle with Dual Pairing that lets you connect two devices at once. Don’t hold back, choose your vibe with Rockerz 333.',
    price: 55,
  },
  {
    img1:  w1 ,
    img2:  w2 ,
    img3:  w3 ,
    img4:  w4 ,
    name: 'Watch Blaze',
    rate: 4,
    rates: 20,
    details:
      'Whatever you need to hustle to your goal — now do it Faster with Blaze. It’s powered by Apollo 3 Blue Plus high-performance processor that makes its interface 25% faster. Navigate through your world effortlessly with its 1.75” HD display — the largest by boAt. We understand your hustle, that’s why its Fast Charge technology gives 24HRS of backup with just 10MINS of charge. Keep your fitness in check with heart rate and SpO2 monitoring, daily activity tracker, and 14 sport modes. Smart Watch Blaze — for trailblazers like you.',
    price: 49,
  },
]
Products.forEach((product, index) => {
  product.id = index + 1
})
